name: CD to EC2 from DockerHub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up DockerHub credentials
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Add SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > devops-key.pem
          chmod 400 devops-key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i devops-key.pem ubuntu@34.219.157.83 << 'EOF'
            docker pull mohammedrs/day6-dockerhub-cd
            docker stop app || true
            docker rm app || true
            docker run -d --name app -p 5000:5000 mohammedrs/day6-dockerhub-cd
          EOF

